name: Tests
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  test:
    name: "run tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
        id: go

      - name: "Check out code"
        uses: actions/checkout@v3

      - name: "test"
        run: |
          go test ./...
